#baseURL = 'https://i14y-ch.github.io/handbook/'
languageCode = 'de-CH'
title = 'Handbuch I14Y-Interoperabilitätsplattform'

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
    
# Language settings
contentDir = "content/"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

# Language configuration
[languages]
[languages.de]
title = "Handbuch I14Y-Interoperabilitätsplattform"
description = "Anleitungen und Informationen zur Interoperabilitätsplattform"
languageName = "Deutsch"
languageCode = "de"
contentDir = "content/de"
weight = 1

[languages.fr]
title = "Manuel I14Y plateforme d’interopérabilité"
description = "Instructions et informations sur la plate-forme d'interopérabilité"
languageName = "Français"
languageCode = "fr"
contentDir = "content/fr"
weight = 2

[languages.it]
title = "Manuale I14Y piattaforma di interoperabilità"
description = "Guida e informazioni sulla piattaforma di interoperabilità"
languageName = "Italian"
languageCode = "it"
contentDir = "content/it"
weight = 3

[languages.rm]
title = "Manual da plattafurma d'interoperabilitad I14Y"
description = ""
languageName = "Rumantsch"
languageCode = "rm"
contentDir = "content/rm"
weight = 4

[languages.en]
title = "Manual I14Y Interoperability Platform"
description = "Manual and Information about the interoperability platform"
languageName = "English"
languageCode = "en"
contentDir = "content/en"
weight = 5

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

# Konfiguration für den Diagramm-Generator Mermaid.
[params.mermaid]
enable = true
theme = "base"

[markup.goldmark.parser.attribute]
block = true
